//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signup_with_Login.dbo_connet
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student_tbl
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Field is Rquired")]
        public string First_Name { get; set; }
        [Required(ErrorMessage = "Field is Rquired")]
        public string Last_Name { get; set; }
        [Required(ErrorMessage = "Field is Rquired")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Field is Rquired")]
        
        public string Password { get; set; }
        [Required(ErrorMessage = "Field is Rquired")]
        public string Practice_Field { get; set; }
        [Required(ErrorMessage = "Field is Rquired")]
        public string Role { get; set; }
    }
}
